# Generated by Django 3.1.2 on 2020-10-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='front_of_card',
            field=models.BooleanField(null=True),
        ),
    ]
